### ISSUE TITLE
typeInElement should trigger keydown and keyup events

### ISSUE THREAD

**Issue by david-bulte** [ngneat/spectator#350] opened 2020-09-28 16:36 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have an input field with a _keydown_ event handler. When the end user enters certain invalid characters, this event handler prevents setting these invalid characters (with "event.preventdefault").
 
When testing this behavior with the _typeInElement_ method, I notice that the _keydown_ event is not triggered, and the invalid characters end up in the input field.

## Expected behavior

It would be nice if the _typeInElement_ method could first issue a keydown event, and handle appropriately when that that one is cancelled,

**Comment by NetanelBasal** [comment] 2020-09-28 16:54
Can you provide a stackblitz example, please?

**Comment by david-bulte** [comment] 2020-09-28 18:45
Here's an example: https://ng-run.com/edit/PSjuW4KzM24stvU6wDeQ?open=src%2Fapp%2Fapp.component.spec.ts&test=true

Note that I get a "require.context is not a function" error when trying to run the test, I am not very familiar with Stackblitz.

Thanks for having a look!

**Comment by NetanelBasal** [comment] 2020-09-28 19:51
The issue is that `typeInElement` doesn't trigger the `keydown` event. You can use `spectator.dispatchKeyboardEvent(f, "keydown", 'w')` but it'll not update the input `value`.

**Comment by david-bulte** [comment] 2020-09-28 20:19
Yeah I tried `dispatchKeyboardEvent` but that doesn't really help me in this case.

Ideally I would be able to test this by just checking the markup, but I understand this is not possible at the moment. Do you have another suggestion how I could test whether the event has been prevented or not? Is it possible to spy on $event?

**Comment by NetanelBasal** [comment] 2020-09-29 05:57
You can make the code more testable. Extract the logic inside the `if` statement to a method, and spy on it.

**Comment by NetanelBasal** [comment] 2020-10-06 04:54
I'm closing the issue.

**Closed by NetanelBasal** 2020-10-06 04:54 UTC
