### ISSUE TITLE
"Navigation triggered outside Angular zone" when creating a routed component with stubsEnabled:  false

### ISSUE THREAD

**Issue by Mautriz** [ngneat/spectator#310] opened 2020-05-23 18:01 UTC
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X ] Support request
[ ] Other... Please describe:
</code></pre>

I was trying out the Router, haven't done anything special, just trying to make it work, I tried following the example but the warning keeps appearing for every iteration
PS: The test passes

```typescript
describe("main app", () => {
	let comp: SpectatorRouting<AppComponent>;
	const createComponent = createRoutingFactory({
		component: AppComponent,
		declarations: [HomePage],
		// providers: [SplashScreen, Platform, StatusBar], 
		imports: [...GLOBAL_MODULES], // Just IonicModule
		stubsEnabled: false,
		routes: [
			{
				path: "home",
				component: HomePage,
			},
		],
	});
	beforeEach(() => {
		comp = createComponent();
	});
	it("should be defined", () => {
		expect(comp).toBeDefined();
	});
});
```
This is the warning I'm receiving with this code 
```bash
 console.warn
      Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

      24 | 
      25 |      beforeEach(() => {
    > 26 |              comp = createComponent();
         |                  
```
```html
<ion-app>
  <ion-router-outlet></ion-router-outlet>
</ion-app>
```
This is probably a very stupid question, can someone help realize why this is happening ? 

I've seen the Issue in the angular repo, they just make use of ```ngZone.run(() => router.dosomething)``` when the warning occurs, the problem here is that I'm not directly calling anything inside the component nor in the test file

Environment: 
Angular version: 9.1.6
jest ^26
spectator 5.7.1
ionic ^5

- Node version: ^12
- Platform: Mac

EDIT: I tried removing all ts code from app.component.ts and all deps, still the same

**Comment by NetanelBasal** [comment] 2020-05-24 04:53
Duplicate of #298

**Closed by NetanelBasal** 2020-05-24 04:53 UTC
