### ISSUE TITLE
Spectator is slow as compared to the ng-bullet

### ISSUE THREAD

**Issue by sozakir** [ngneat/spectator#354] opened 2020-10-07 11:35 UTC
## I'm submitting a...

<pre><code>
[ * ] Performance issue
</code></pre>

## Current behavior
I want to incorporate **spectator** in my test suit of around `~1500` unit tests and are increasing. 

I have earlier used **ng-bullet**, with **karma parallel** in order to speed up my tests. 

I have recently upgraded my app to **Angular 9**. I found out this issue https://github.com/topnotch48/ng-bullet-workspace/issues/8. I am worried about the performance of my tests suit in the long run. Therefore I want to switch to **spectator**. 

But performance is my concern here. I have used playground code and _converted it to ng-bullet_. I found the code with ng-bullet is **faster** as compared to spectator. My assumption is that if I completely switched by test suit to spectator it would slow down my current test suite.

Am I doing something wrong here or spectator main concern is to reduce the boiler plate rather than reducing the time?
I clearly sees spectator is taking more time.

## Minimal reproduction of the problem with instructions
Here sample stackblitz code with ng-bullet
https://stackblitz.com/edit/angular-testing-spectator-enm3yo?file=app/hello.component.spec.ts 

Code using spectator
https://stackblitz.com/edit/angular-testing-spectator

I have also tested this on my proprietary company code, I have replaced the ng-bullet code with spectator and the time **increased** for both `the component and the service`. I can create a sample project and replicate it but I am busy with my own work. As the author of ng-bullet pointed out spectator is using the same method for speeding up the test and provide additional benefits. But after finding the time results are otherwise. 

Any comments @NetanelBasal ??

## Environment

<pre><code>
Angular version: 9

Browser:
- [ *] Chrome (desktop) Version 85.0.4183.121 (Official Build) (64-bit)

 
For Tooling issues:
- Node version: 12.14.1
- Platform:  Windows 10

Others:

</code></pre>

**Comment by ntvsx193** [comment] 2020-10-13 14:09
same time, see:
![image](https://user-images.githubusercontent.com/2971095/95871858-d1acd900-0d76-11eb-8b27-6252b83ac1f1.png)
![image](https://user-images.githubusercontent.com/2971095/95871895-dd000480-0d76-11eb-8d70-f5a4d38c5283.png)

**Comment by sozakir** [comment] 2020-10-15 11:17
Hi @ntvsx193 , I will create a demo app and show you my finding by the weekend.

**Comment by benelliott** [comment] 2020-10-15 15:51
> Am I doing something wrong here or spectator main concern is to reduce the boiler plate rather than reducing the time?

You're right, Spectator isn't designed to speed up unit tests like ng-bullet is. It's just meant to provide a more approachable testing API than what you get out of the box with Angular.

That said, there have been some attempts to integrate ng-bullet: https://github.com/ngneat/spectator/issues/89 and https://github.com/ngneat/spectator/pull/100

The PR was eventually closed because it didn't seem to speed things up sufficiently, and Ivy was around the corner.

So I'll close this as a duplicate of #89 unless you believe the situation has changed considerably since then?

**Comment by sozakir** [comment] 2020-10-20 11:49
@benelliott I am busy last week and i have seen in my app using Ivy, I am able to decrease the angular test execution time when I am using ng-bullet. Can you re open this issue. I think of create a demo app by weekend and try to use ng-bullet code in the spectator on my local and create a PR.

**Comment by johncrim** [comment] 2020-10-22 17:48
You might try switching to Jest (from karma) - it's generally regarded as more performant than launching a browser and running your tests in a browser (we use Jest and spectator). I don't have benchmarks, but it worked well for this guy:
https://dev.to/dylanwatsonsoftware/make-your-angular-tests-1000-faster-by-switching-from-karma-to-jest-1n33

The downside of Jest is it uses jsdom, which doesn't have all the functionality of a real browser. So another option is making browser dependent tests use karma, and more generic tests use Jest.

The biggest issues with using Jest right now (IMO) are:
* Initial setup is kind of a hassle
* jest-preset-angular doesn't yet support using the Ivy viewengine for tests, so the old compiler is used and jest can't yet benefit from the ivy perf improvements

**Comment by sozakir** [comment] 2020-10-23 05:44
@johncrim can we use jest and jasmine together in the same project?. Could shared some info regarding your number of tests and their total execution time?

**Comment by johncrim** [comment] 2020-10-25 14:51
Jest has a very jasmine like test library, though I'm not sure if that's what you're asking. I use jest and (karma+jasmine) in the same project, just using different file extensions (I use `.karma.spec` for karma tests, and `.spec` for Jest tests).

I have 365 tests across 75 test suites in 8 projects, which takes 74s (just now). That's Jest only, we have some karma tests on top of that.

Like I said, that should speed up further once jest-preset-angular has ivy support.

**Comment by NetanelBasal** [comment] 2020-11-25 17:14
It'll be great if someone can check this optimization - https://github.com/angular/angular/issues/31834.

**Comment by ssuperczynski** [comment] 2020-11-26 09:16
@NetanelBasal 

MacBook Pro
Proc: 2,2 GHz 6-Core Intel Core i7
Mem: 16 GB 2400 MHz DDR4

Angular: 10.0.8
Test runner: Jest@26.0.1

Results (40 components fully use Spectator):
Test Suites: 59 total
Tests: 1369 total

**Without fix:**
191.889 s

**With fix:** `getTestBed().inject(ɵDomSharedStylesHost).ngOnDestroy();`
192.708 s

**With fix:** `window.document.querySelectorAll("style").forEach((style: HTMLStyleElement) => style.remove());`
185.946 s


And small heads up, without fix but by adding:

```ts
import { cacheTestingModule } from 'ng-cache-testing-module';
describe() => {
  ...
  cacheTestingModule();
  ...
```
55.272 s

**Comment by NetanelBasal** [comment] 2020-11-27 05:30
@ssuperczynski, based on your information, It doesn't have much effect. I'm not familiar with ng-cache-testing-module, and I don't know if it can bring side effects to existing code.

**Comment by ntvsx193** [comment] 2020-11-28 08:09
> @NetanelBasal
> 
> MacBook Pro
> **Proc**: 2,2 GHz 6-Core Intel Core i7
> **Mem**: 16 GB 2400 MHz DDR4
> 
> **Angular**: 10.0.8
> **Test runner**: Jest@26.0.1
> 
> Results (40 components fully use Spectator):
> Test Suites: 59 total
> Tests: 1369 total
> 
> **Without fix:**
> Time: 191.889 s
> 
> **With fix:** `getTestBed().inject(ɵDomSharedStylesHost).ngOnDestroy();`
> Time: 192.708 s
> 
> **With fix:** `window.document.querySelectorAll("style").forEach((style: HTMLStyleElement) => style.remove());`
> Time: 185.946 s
> 
> And small heads up, without fix but by adding:
> 
> ```ts
> import { cacheTestingModule } from 'ng-cache-testing-module';
> describe() => {
>   ...
>   cacheTestingModule();
>   ...
> }
> ```
> 
> Time: 55.272 s

Why are u use jest it performance with fix remove styles?
Jest run workaround in clearable always.
This fix relevant only for karma + jasmine where it has shared workaround.

**Closed** 2021-01-28 05:15 UTC
